import json

import numpy as np

from .config import IMASExportMetadata, RectangularGrid2D
from .evaluate import equilibrium_interpolators, evaluate_interpolator_on_grid


def _rectangular_topology(grid: RectangularGrid2D):
    r_axis, z_axis = grid.axes()
    nr = len(r_axis)
    nz = len(z_axis)

    def node_id(i_r, i_z):
        return i_r * nz + i_z + 1

    node_coords = []
    for i_r, r_val in enumerate(r_axis):
        for i_z, z_val in enumerate(z_axis):
            node_coords.append((node_id(i_r, i_z), float(r_val), float(z_val)))

    horizontal_edges = []
    vertical_edges = []
    edge_id = 1
    for i_r in range(nr):
        for i_z in range(nz - 1):
            horizontal_edges.append((edge_id, node_id(i_r, i_z), node_id(i_r, i_z + 1)))
            edge_id += 1
    for i_r in range(nr - 1):
        for i_z in range(nz):
            vertical_edges.append((edge_id, node_id(i_r, i_z), node_id(i_r + 1, i_z)))
            edge_id += 1

    horizontal_lookup = {(n1, n2): idx for idx, n1, n2 in horizontal_edges}
    vertical_lookup = {(n1, n2): idx for idx, n1, n2 in vertical_edges}

    cells = []
    cell_id = 1
    for i_r in range(nr - 1):
        for i_z in range(nz - 1):
            n00 = node_id(i_r, i_z)
            n01 = node_id(i_r, i_z + 1)
            n10 = node_id(i_r + 1, i_z)
            n11 = node_id(i_r + 1, i_z + 1)
            cells.append(
                (
                    cell_id,
                    [n00, n01, n11, n10],
                    [
                        horizontal_lookup[(n00, n01)],
                        vertical_lookup[(n01, n11)],
                        horizontal_lookup[(n10, n11)],
                        vertical_lookup[(n00, n10)],
                    ],
                )
            )
            cell_id += 1

    return {
        "nodes": node_coords,
        "edges": horizontal_edges + vertical_edges,
        "cells": cells,
    }


def _populate_rectangular_grid_ggd(eq, grid: RectangularGrid2D, time_value: float):
    topology = _rectangular_topology(grid)

    eq.grids_ggd.resize(1)
    grids_ggd = eq.grids_ggd[0]
    grids_ggd.time = float(time_value)
    grids_ggd.grid.resize(1)
    grid_node = grids_ggd.grid[0]
    grid_node.identifier.name = "rectangular_rz"
    grid_node.identifier.index = 1
    grid_node.identifier.description = "Regular cylindrical (R,Z) grid generated by hdg_postprocess."

    grid_node.space.resize(1)
    space = grid_node.space[0]
    space.identifier.name = "rectangular_rz_space"
    space.identifier.index = 1
    space.identifier.description = "One rectangular cylindrical (R,Z) space."
    space.geometry_type.name = "rectangular"
    space.geometry_type.index = 1
    space.geometry_type.description = "Structured rectangular cylindrical grid."
    space.coordinates_type.resize(2)
    space.coordinates_type[0].name = "R"
    space.coordinates_type[0].index = 1
    space.coordinates_type[0].description = "Cylindrical major radius."
    space.coordinates_type[1].name = "Z"
    space.coordinates_type[1].index = 2
    space.coordinates_type[1].description = "Vertical coordinate."

    space.objects_per_dimension.resize(3)

    node_objects = space.objects_per_dimension[0]
    node_objects.geometry_content.name = "nodes"
    node_objects.geometry_content.index = 1
    node_objects.geometry_content.description = "Point objects."
    node_objects.object.resize(len(topology["nodes"]))
    for idx, (_, r_val, z_val) in enumerate(topology["nodes"]):
        obj = node_objects.object[idx]
        obj.nodes = np.array([idx + 1], dtype=np.int32)
        obj.geometry = np.array([r_val, z_val], dtype=float)

    edge_objects = space.objects_per_dimension[1]
    edge_objects.geometry_content.name = "edges"
    edge_objects.geometry_content.index = 2
    edge_objects.geometry_content.description = "Line-segment objects."
    edge_objects.object.resize(len(topology["edges"]))
    for idx, (_, node_a, node_b) in enumerate(topology["edges"]):
        obj = edge_objects.object[idx]
        obj.nodes = np.array([node_a, node_b], dtype=np.int32)

    cell_objects = space.objects_per_dimension[2]
    cell_objects.geometry_content.name = "cells"
    cell_objects.geometry_content.index = 3
    cell_objects.geometry_content.description = "Quadrilateral surface objects."
    cell_objects.object.resize(len(topology["cells"]))
    for idx, (_, nodes, edges) in enumerate(topology["cells"]):
        obj = cell_objects.object[idx]
        obj.nodes = np.array(nodes, dtype=np.int32)
        obj.boundary.resize(len(edges))
        for b_idx, edge_id in enumerate(edges):
            obj.boundary[b_idx].index = edge_id

    grid_node.grid_subset.resize(2)
    nodes_subset = grid_node.grid_subset[0]
    nodes_subset.identifier.name = "nodes"
    nodes_subset.identifier.index = 1
    nodes_subset.identifier.description = "All rectangular grid nodes."
    nodes_subset.dimension = 1
    nodes_subset.element.resize(1)
    nodes_subset.element[0].object.resize(len(topology["nodes"]))
    for idx in range(len(topology["nodes"])):
        ref = nodes_subset.element[0].object[idx]
        ref.dimension = 1
        ref.space = 1
        ref.index = idx + 1

    cells_subset = grid_node.grid_subset[1]
    cells_subset.identifier.name = "cells"
    cells_subset.identifier.index = 2
    cells_subset.identifier.description = "All rectangular surface cells."
    cells_subset.dimension = 2
    cells_subset.element.resize(1)
    cells_subset.element[0].object.resize(len(topology["cells"]))
    for idx in range(len(topology["cells"])):
        ref = cells_subset.element[0].object[idx]
        ref.dimension = 3
        ref.space = 1
        ref.index = idx + 1

    return grid_node


def _equilibrium_metadata(solution, metadata, grid):
    extracted = {
        "grid_shape": [grid.nr, grid.nz],
        "grid_r_range_m": [grid.r_min, grid.r_max],
        "grid_z_range_m": [grid.z_min, grid.z_max],
        "representation_note": "Exported on a rectangular cylindrical (R,Z) mesh through equilibrium.grids_ggd/time_slice[0].ggd.",
        "ggd_grid_name": "rectangular_rz",
        "ggd_grid_description": "Regular cylindrical (R,Z) rectangular grid with explicit node, edge, and cell topology.",
        "ggd_grid_subset": "All exported equilibrium fields currently live on the nodes subset.",
        "ggd_value_ordering": "Node values are flattened from meshgrid(indexing='ij') in C order, so R is the slow axis and Z the fast axis.",
        "poloidal_flux_export_note": (
            metadata.poloidal_flux_convention
            or (
                "Poloidal flux is exported exactly as stored in the HDG solution; "
                "normalization and sign may depend on solver version, so the person "
                "doing the IMAS export should verify the convention."
            )
        ),
        "j_phi_export_note": (
            "Exported j_phi currently comes from the HDG Jtor field; in current usage "
            "this is typically the Ohmic contribution, and the person doing the IMAS "
            "export should verify the sign convention."
        ),
    }
    if solution.summary.equilibrium.axis.r is not None and solution.summary.equilibrium.axis.z is not None:
        extracted["magnetic_axis_r_m"] = float(solution.summary.equilibrium.axis.r)
        extracted["magnetic_axis_z_m"] = float(solution.summary.equilibrium.axis.z)
    return extracted


def build_equilibrium_ids(solution, metadata: IMASExportMetadata, grid: RectangularGrid2D):
    """Build a rectangular-grid equilibrium IDS from one HDG solution."""

    import imas

    solution.assembly.full()
    solution.assembly.simple()
    solution.equilibrium.define_axis()

    eq = imas.IDSFactory().equilibrium()
    eq.ids_properties.homogeneous_time = imas.ids_defs.IDS_TIME_MODE_HOMOGENEOUS
    eq.time = np.array([float(metadata.time)])
    eq.time_slice.resize(1)

    ts = eq.time_slice[0]
    ts.time = float(metadata.time)
    _populate_rectangular_grid_ggd(eq, grid, float(metadata.time))
    ts.ggd.resize(1)
    ggd = ts.ggd[0]

    r_grid, z_grid = grid.mesh()
    interpolators = equilibrium_interpolators(solution)
    psi_values = evaluate_interpolator_on_grid(interpolators["psi"], r_grid=r_grid, z_grid=z_grid).reshape(-1)
    br_values = evaluate_interpolator_on_grid(interpolators["br"], r_grid=r_grid, z_grid=z_grid).reshape(-1)
    bz_values = evaluate_interpolator_on_grid(interpolators["bz"], r_grid=r_grid, z_grid=z_grid).reshape(-1)
    bphi_values = evaluate_interpolator_on_grid(interpolators["bphi"], r_grid=r_grid, z_grid=z_grid).reshape(-1)
    r_values = r_grid.reshape(-1)
    z_values = z_grid.reshape(-1)

    def _store_ggd_field(field_name, values):
        field = getattr(ggd, field_name)
        field.resize(1)
        field[0].grid_index = 1
        field[0].grid_subset_index = 1
        field[0].values = values

    _store_ggd_field("r", r_values)
    _store_ggd_field("z", z_values)
    _store_ggd_field("psi", psi_values)
    _store_ggd_field("b_field_r", br_values)
    _store_ggd_field("b_field_z", bz_values)
    _store_ggd_field("b_field_phi", bphi_values)
    if interpolators["jphi"] is not None:
        jphi_values = evaluate_interpolator_on_grid(interpolators["jphi"], r_grid=r_grid, z_grid=z_grid).reshape(-1)
        _store_ggd_field("j_phi", jphi_values)

    axis = solution.summary.equilibrium.axis
    if axis.r is not None and axis.z is not None:
        ts.global_quantities.magnetic_axis.r = float(axis.r)
        ts.global_quantities.magnetic_axis.z = float(axis.z)

    finite_psi = psi_values[np.isfinite(psi_values)]
    if finite_psi.size:
        ts.global_quantities.psi_axis = float(np.nanmin(finite_psi))

    eq.code.name = "SOLEDGE-HDG"
    eq.code.repository = "hdg_postprocess"
    eq.code.description = "Equilibrium exported from SOLEDGE-HDG by hdg_postprocess."
    eq.code.parameters = json.dumps(_equilibrium_metadata(solution, metadata, grid), sort_keys=True)

    return eq


def put_equilibrium(entry, solution, metadata: IMASExportMetadata, grid: RectangularGrid2D):
    """Build and store one equilibrium IDS in the provided IMAS DBEntry."""

    equilibrium = build_equilibrium_ids(solution, metadata, grid)
    entry.put(equilibrium, metadata.occurrence)
    return equilibrium
