import json

import numpy as np

from hdg_postprocess.routines.interpolators import SoledgeHDG2DInterpolator

from .config import IMASExportMetadata, RectangularGrid2D


def _evaluate_rect(interpolator, r_grid, z_grid):
    values = np.empty_like(r_grid, dtype=float)
    for index in np.ndindex(r_grid.shape):
        values[index] = interpolator(r_grid[index], z_grid[index])
    return values


def _equilibrium_interpolators(solution):
    if solution.mesh.metadata.reference_element is None:
        raise ValueError(
            "Equilibrium export on a rectangular grid requires solution.mesh.metadata.reference_element. "
            "Load it first with hdg_postprocess.api.load_reference_element(...) or configure_solution_setup(...)."
        )
    solution.sample.define_interpolators()
    glob_eq = solution.views.glob.equilibrium
    sample = solution.interpolators.sample

    interpolators = {
        "br": SoledgeHDG2DInterpolator.instance(
            sample, glob_eq.magnetic_field[:, :, 0], limit=False, default_value=np.nan
        ),
        "bz": SoledgeHDG2DInterpolator.instance(
            sample, glob_eq.magnetic_field[:, :, 1], limit=False, default_value=np.nan
        ),
        "bphi": SoledgeHDG2DInterpolator.instance(
            sample, glob_eq.magnetic_field[:, :, 2], limit=False, default_value=np.nan
        ),
        "psi": SoledgeHDG2DInterpolator.instance(
            sample, glob_eq.poloidal_flux, limit=False, default_value=np.nan
        ),
    }
    if glob_eq.jtor is not None:
        interpolators["jphi"] = SoledgeHDG2DInterpolator.instance(
            sample, glob_eq.jtor, limit=False, default_value=np.nan
        )
    return interpolators


def _equilibrium_metadata(solution, metadata, grid):
    extracted = {
        "grid_shape": [grid.nr, grid.nz],
        "grid_r_range_m": [grid.r_min, grid.r_max],
        "grid_z_range_m": [grid.z_min, grid.z_max],
        "poloidal_flux_export_note": (
            metadata.poloidal_flux_convention
            or "Poloidal flux is exported exactly as stored in the HDG solution; normalization may depend on solver version."
        ),
    }
    if solution.summary.equilibrium.axis.r is not None and solution.summary.equilibrium.axis.z is not None:
        extracted["magnetic_axis_r_m"] = float(solution.summary.equilibrium.axis.r)
        extracted["magnetic_axis_z_m"] = float(solution.summary.equilibrium.axis.z)
    return extracted


def build_equilibrium_ids(solution, metadata: IMASExportMetadata, grid: RectangularGrid2D):
    """Build a rectangular-grid equilibrium IDS from one HDG solution."""

    import imas

    solution.assembly.full()
    solution.assembly.simple()
    solution.equilibrium.define_axis()

    eq = imas.IDSFactory().equilibrium()
    eq.ids_properties.homogeneous_time = imas.ids_defs.IDS_TIME_MODE_HOMOGENEOUS
    eq.time = np.array([float(metadata.time)])
    eq.time_slice.resize(1)

    ts = eq.time_slice[0]
    ts.time = float(metadata.time)
    ts.profiles_2d.resize(1)
    p2 = ts.profiles_2d[0]

    r_axis, z_axis = grid.axes()
    r_grid, z_grid = grid.mesh()
    p2.grid.dim1 = r_axis
    p2.grid.dim2 = z_axis
    p2.grid_type.index = 1
    p2.grid_type.name = "rectangular"
    p2.grid_type.description = "Regular (R,Z) export grid generated by hdg_postprocess."

    interpolators = _equilibrium_interpolators(solution)
    p2.r = r_grid
    p2.z = z_grid
    p2.psi = _evaluate_rect(interpolator=interpolators["psi"], r_grid=r_grid, z_grid=z_grid)
    p2.b_field_r = _evaluate_rect(interpolator=interpolators["br"], r_grid=r_grid, z_grid=z_grid)
    p2.b_field_z = _evaluate_rect(interpolator=interpolators["bz"], r_grid=r_grid, z_grid=z_grid)
    p2.b_field_phi = _evaluate_rect(interpolator=interpolators["bphi"], r_grid=r_grid, z_grid=z_grid)
    if "jphi" in interpolators:
        p2.j_phi = _evaluate_rect(interpolator=interpolators["jphi"], r_grid=r_grid, z_grid=z_grid)

    axis = solution.summary.equilibrium.axis
    if axis.r is not None and axis.z is not None:
        ts.global_quantities.magnetic_axis.r = float(axis.r)
        ts.global_quantities.magnetic_axis.z = float(axis.z)

    finite_psi = p2.psi[np.isfinite(p2.psi)]
    if finite_psi.size:
        ts.global_quantities.psi_axis = float(np.nanmin(finite_psi))

    eq.code.name = "SOLEDGE-HDG"
    eq.code.repository = "hdg_postprocess"
    eq.code.description = "Equilibrium exported from SOLEDGE-HDG by hdg_postprocess."
    eq.code.parameters = json.dumps(_equilibrium_metadata(solution, metadata, grid), sort_keys=True)

    return eq


def put_equilibrium(entry, solution, metadata: IMASExportMetadata, grid: RectangularGrid2D):
    """Build and store one equilibrium IDS in the provided IMAS DBEntry."""

    equilibrium = build_equilibrium_ids(solution, metadata, grid)
    entry.put(equilibrium, metadata.occurrence)
    return equilibrium
