import json

import numpy as np

from .config import IMASExportMetadata, RectangularGrid2D
from .evaluate import equilibrium_interpolators, evaluate_interpolator_on_grid


def _equilibrium_metadata(solution, metadata, grid):
    extracted = {
        "grid_shape": [grid.nr, grid.nz],
        "grid_r_range_m": [grid.r_min, grid.r_max],
        "grid_z_range_m": [grid.z_min, grid.z_max],
        "representation_note": "Exported on a rectangular cylindrical (R,Z) mesh through equilibrium.grids_ggd/time_slice[0].ggd.",
        "ggd_grid_name": "rectangular_rz",
        "ggd_grid_description": "Flattened regular cylindrical (R,Z) grid generated by hdg_postprocess.",
        "ggd_value_ordering": "Values are flattened from meshgrid(indexing='ij') in C order, so R is the slow axis and Z the fast axis.",
        "poloidal_flux_export_note": (
            metadata.poloidal_flux_convention
            or (
                "Poloidal flux is exported exactly as stored in the HDG solution; "
                "normalization and sign may depend on solver version, so the person "
                "doing the IMAS export should verify the convention."
            )
        ),
        "j_phi_export_note": (
            "Exported j_phi currently comes from the HDG Jtor field; in current usage "
            "this is typically the Ohmic contribution, and the person doing the IMAS "
            "export should verify the sign convention."
        ),
    }
    if solution.summary.equilibrium.axis.r is not None and solution.summary.equilibrium.axis.z is not None:
        extracted["magnetic_axis_r_m"] = float(solution.summary.equilibrium.axis.r)
        extracted["magnetic_axis_z_m"] = float(solution.summary.equilibrium.axis.z)
    return extracted


def build_equilibrium_ids(solution, metadata: IMASExportMetadata, grid: RectangularGrid2D):
    """Build a rectangular-grid equilibrium IDS from one HDG solution."""

    import imas

    solution.assembly.full()
    solution.assembly.simple()
    solution.equilibrium.define_axis()

    eq = imas.IDSFactory().equilibrium()
    eq.ids_properties.homogeneous_time = imas.ids_defs.IDS_TIME_MODE_HOMOGENEOUS
    eq.time = np.array([float(metadata.time)])
    eq.time_slice.resize(1)

    ts = eq.time_slice[0]
    ts.time = float(metadata.time)
    eq.grids_ggd.resize(1)
    eq.grids_ggd[0].time = float(metadata.time)
    eq.grids_ggd[0].grid.resize(1)
    grid_node = eq.grids_ggd[0].grid[0]
    grid_node.identifier.name = "rectangular_rz"
    grid_node.identifier.index = 1
    grid_node.identifier.description = "Flattened regular cylindrical (R,Z) grid generated by hdg_postprocess."
    grid_node.path = "rectangular_rz"
    ts.ggd.resize(1)
    ggd = ts.ggd[0]

    r_grid, z_grid = grid.mesh()
    interpolators = equilibrium_interpolators(solution)
    psi_values = evaluate_interpolator_on_grid(interpolators["psi"], r_grid=r_grid, z_grid=z_grid).reshape(-1)
    br_values = evaluate_interpolator_on_grid(interpolators["br"], r_grid=r_grid, z_grid=z_grid).reshape(-1)
    bz_values = evaluate_interpolator_on_grid(interpolators["bz"], r_grid=r_grid, z_grid=z_grid).reshape(-1)
    bphi_values = evaluate_interpolator_on_grid(interpolators["bphi"], r_grid=r_grid, z_grid=z_grid).reshape(-1)
    r_values = r_grid.reshape(-1)
    z_values = z_grid.reshape(-1)

    def _store_ggd_field(field_name, values):
        field = getattr(ggd, field_name)
        field.resize(1)
        field[0].grid_index = 1
        field[0].values = values

    _store_ggd_field("r", r_values)
    _store_ggd_field("z", z_values)
    _store_ggd_field("psi", psi_values)
    _store_ggd_field("b_field_r", br_values)
    _store_ggd_field("b_field_z", bz_values)
    _store_ggd_field("b_field_phi", bphi_values)
    if interpolators["jphi"] is not None:
        jphi_values = evaluate_interpolator_on_grid(interpolators["jphi"], r_grid=r_grid, z_grid=z_grid).reshape(-1)
        _store_ggd_field("j_phi", jphi_values)

    axis = solution.summary.equilibrium.axis
    if axis.r is not None and axis.z is not None:
        ts.global_quantities.magnetic_axis.r = float(axis.r)
        ts.global_quantities.magnetic_axis.z = float(axis.z)

    finite_psi = psi_values[np.isfinite(psi_values)]
    if finite_psi.size:
        ts.global_quantities.psi_axis = float(np.nanmin(finite_psi))

    eq.code.name = "SOLEDGE-HDG"
    eq.code.repository = "hdg_postprocess"
    eq.code.description = "Equilibrium exported from SOLEDGE-HDG by hdg_postprocess."
    eq.code.parameters = json.dumps(_equilibrium_metadata(solution, metadata, grid), sort_keys=True)

    return eq


def put_equilibrium(entry, solution, metadata: IMASExportMetadata, grid: RectangularGrid2D):
    """Build and store one equilibrium IDS in the provided IMAS DBEntry."""

    equilibrium = build_equilibrium_ids(solution, metadata, grid)
    entry.put(equilibrium, metadata.occurrence)
    return equilibrium
