import numpy as np

from .config import RectangularGrid2D


def rectangular_topology(grid: RectangularGrid2D):
    r_axis, z_axis = grid.axes()
    nr = len(r_axis)
    nz = len(z_axis)

    def node_id(i_r, i_z):
        return i_r * nz + i_z + 1

    node_coords = []
    for i_r, r_val in enumerate(r_axis):
        for i_z, z_val in enumerate(z_axis):
            node_coords.append((node_id(i_r, i_z), float(r_val), float(z_val)))

    horizontal_edges = []
    vertical_edges = []
    edge_id = 1
    for i_r in range(nr):
        for i_z in range(nz - 1):
            horizontal_edges.append((edge_id, node_id(i_r, i_z), node_id(i_r, i_z + 1)))
            edge_id += 1
    for i_r in range(nr - 1):
        for i_z in range(nz):
            vertical_edges.append((edge_id, node_id(i_r, i_z), node_id(i_r + 1, i_z)))
            edge_id += 1

    horizontal_lookup = {(n1, n2): idx for idx, n1, n2 in horizontal_edges}
    vertical_lookup = {(n1, n2): idx for idx, n1, n2 in vertical_edges}

    cells = []
    cell_id = 1
    for i_r in range(nr - 1):
        for i_z in range(nz - 1):
            n00 = node_id(i_r, i_z)
            n01 = node_id(i_r, i_z + 1)
            n10 = node_id(i_r + 1, i_z)
            n11 = node_id(i_r + 1, i_z + 1)
            cells.append(
                (
                    cell_id,
                    [n00, n01, n11, n10],
                    [
                        horizontal_lookup[(n00, n01)],
                        vertical_lookup[(n01, n11)],
                        horizontal_lookup[(n10, n11)],
                        vertical_lookup[(n00, n10)],
                    ],
                )
            )
            cell_id += 1

    return {
        "nodes": node_coords,
        "edges": horizontal_edges + vertical_edges,
        "cells": cells,
    }


def populate_rectangular_grid_ggd_array(grid_array, grid: RectangularGrid2D, time_value: float, *, grid_name="rectangular_rz"):
    topology = rectangular_topology(grid)

    grid_array.resize(1)
    grids_ggd = grid_array[0]
    grids_ggd.time = float(time_value)
    if hasattr(grids_ggd, "grid"):
        grids_ggd.grid.resize(1)
        grid_node = grids_ggd.grid[0]
    else:
        grid_node = grids_ggd
    grid_node.identifier.name = grid_name
    grid_node.identifier.index = 1
    grid_node.identifier.description = "Regular cylindrical (R,Z) grid generated by hdg_postprocess."

    grid_node.space.resize(1)
    space = grid_node.space[0]
    space.identifier.name = f"{grid_name}_space"
    space.identifier.index = 1
    space.identifier.description = "One rectangular cylindrical (R,Z) space."
    space.geometry_type.name = "standard"
    space.geometry_type.index = 0
    space.geometry_type.description = "Structured rectangular cylindrical grid."
    space.coordinates_type.resize(2)
    space.coordinates_type[0].name = "R"
    space.coordinates_type[0].description = "Cylindrical major radius."
    space.coordinates_type[1].name = "Z"
    space.coordinates_type[1].description = "Vertical coordinate."

    space.objects_per_dimension.resize(3)

    node_objects = space.objects_per_dimension[0]
    node_objects.geometry_content.name = "nodes"
    node_objects.geometry_content.index = 1
    node_objects.geometry_content.description = "Point objects."
    node_objects.object.resize(len(topology["nodes"]))
    for idx, (_, r_val, z_val) in enumerate(topology["nodes"]):
        obj = node_objects.object[idx]
        obj.nodes = np.array([idx + 1], dtype=np.int32)
        obj.geometry = np.array([r_val, z_val], dtype=float)

    edge_objects = space.objects_per_dimension[1]
    edge_objects.geometry_content.name = "edges"
    edge_objects.geometry_content.index = 2
    edge_objects.geometry_content.description = "Line-segment objects."
    edge_objects.object.resize(len(topology["edges"]))
    for idx, (_, node_a, node_b) in enumerate(topology["edges"]):
        obj = edge_objects.object[idx]
        obj.nodes = np.array([node_a, node_b], dtype=np.int32)

    cell_objects = space.objects_per_dimension[2]
    cell_objects.geometry_content.name = "cells"
    cell_objects.geometry_content.index = 3
    cell_objects.geometry_content.description = "Quadrilateral surface objects."
    cell_objects.object.resize(len(topology["cells"]))
    for idx, (_, nodes, edges) in enumerate(topology["cells"]):
        obj = cell_objects.object[idx]
        obj.nodes = np.array(nodes, dtype=np.int32)
        obj.boundary.resize(len(edges))
        for b_idx, edge_id in enumerate(edges):
            obj.boundary[b_idx].index = edge_id

    grid_node.grid_subset.resize(2)
    nodes_subset = grid_node.grid_subset[0]
    nodes_subset.identifier.name = "nodes"
    nodes_subset.identifier.index = 1
    nodes_subset.identifier.description = "All rectangular grid nodes."
    nodes_subset.dimension = 1
    nodes_subset.element.resize(1)
    nodes_subset.element[0].object.resize(len(topology["nodes"]))
    for idx in range(len(topology["nodes"])):
        ref = nodes_subset.element[0].object[idx]
        ref.dimension = 1
        ref.space = 1
        ref.index = idx + 1

    cells_subset = grid_node.grid_subset[1]
    cells_subset.identifier.name = "cells"
    cells_subset.identifier.index = 2
    cells_subset.identifier.description = "All rectangular surface cells."
    cells_subset.dimension = 2
    cells_subset.element.resize(1)
    cells_subset.element[0].object.resize(len(topology["cells"]))
    for idx in range(len(topology["cells"])):
        ref = cells_subset.element[0].object[idx]
        ref.dimension = 3
        ref.space = 1
        ref.index = idx + 1

    return grid_node


def populate_rectangular_grid_ggd(ids_with_grids_ggd, grid: RectangularGrid2D, time_value: float, *, grid_name="rectangular_rz"):
    return populate_rectangular_grid_ggd_array(
        ids_with_grids_ggd.grids_ggd,
        grid,
        time_value,
        grid_name=grid_name,
    )
